version: "3"
services:
  postgres:
    hostname: postgres
    image: postgres
    volumes:
      - ./dockerization/tests/postgres/migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  feeder:
    hostname: feeder
    build:
      context: .
      dockerfile: dockerization/feeder/Dockerfile
    ports:
      - 1234:1234

  aucote:
    build:
      context: .
      dockerfile: dockerization/tests/Dockerfile
    volumes:
      - ./:/src
    environment:
      AUCOTE_TEST_POSTGRES: 'postgresql://test_aucote:test_aucote@postgres/test_aucote'
      LD_LIBRARY_PATH: /usr/local/lib64
    entrypoint:
      - .ci/run_all.sh
    working_dir: /src
    depends_on:
      - postgres
      - feeder
