version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    volumes:
      - ./dockerization/hardened/postgres/migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  aucote:
    container_name: aucote
    hostname: aucote
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    environment:
      LD_LIBRARY_PATH: /usr/local/lib
    command: bash -c "python3 aucote.py --syncdb --cfg aucote_cfg.yaml.example"
    working_dir: /src
    depends_on:
      - postgres
      - feeder
  feeder:
    container_name: feeder
    hostname: feeder
    build:
      context: .
      dockerfile: dockerization/feeder/Dockerfile
    ports:
      - 1234:1234
    expose:
      - 1234